routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home',function(){
//     return view('welcome');
// });
// Route::get('/homee','HomeController@index');
Route::group(['prefix'=>'admin'],function(){
    Auth::routes(['verify'=>true,'register'=>true]);
});

Route::group(['middleware' => 'auth','prefix'=>'admin'],function(){

    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');

    Route::resource('/users','UserController');
    
    Route::resource('/categories','CategoryController');

    Route::resource('/foods','FoodController');

    Route::resource('/deliverymens','DeliverymenController');

    Route::resource('/deliveries','DeliveryController');

    Route::resource('/customers','CustomerController');

    Route::resource('/orderfoods','OrderfoodController');

    Route::get('/search/users','UserController@search');

    Route::get('/search/orderfoods','OrderfoodController@search');

    Route::get('/search/orders','OrderController@search');

    Route::get('/search/foods','FoodController@search');

    Route::get('/search/deliverymens','DeliverymenController@search');

    Route::get('/search/deliveries','DeliveryController@search');

    Route::get('/search/customers','CustomerController@search');

    Route::get('/search/categories','CategoryController@search');

    Route::get('/orders/active/{id?}','OrderController@active_order')->name('orders.active');

    Route::get('/orders/decline/{id?}','OrderController@decline_order')->name('orders.decline');

    Route::get('/deliverymens/available/{id?}','DeliverymenController@available')->name('deliverymens.available');

    Route::get('/deliverymens/unavailable/{id?}','DeliverymenController@unavailable')->name('deliverymens.unavailable');

    Route::get('/deliveries/finish/{id?}','DeliveryController@finish')->name('deliveries.finish');

    Route::resource('/orders',"OrderController"); 

});

Route::get('/login','Auth\LoginController@showCustomerLoginForm')->name('login.customer');

Route::post('/login','Auth\LoginController@customerLogin');

Route::get('/register','Auth\LoginController@showCustomerRegisterForm')->name('register.customer');

Route::post('/register','Auth\LoginController@customerRegister');

Route::post('/logout','Auth\LoginController@logout');

Route::view('/','frontend.index')->name('asdf');

Route::get('/shop/filter','FoodController@sortCategory');

Route::get('/shop','FoodController@allFood')->name('shop');

Route::view('/about','frontend.about');

Route::view('/contact','frontend.contact');

Route::group(['middleware' => ['auth:customer','verified']],function(){
    Route::get('/cart','OrderController@cart');

    Route::post('/gotocheck','OrderController@goToCheck')->name('gotocheck');

    Route::get('/orders','OrderController@allOrder')->name('order');

    Route::get('/orders/delete/{id?}','OrderController@destroyOrder');

    Route::get('/profile','ProfileController@index')->name('profile');

    Route::post('/profilepic-update/{id?}','ProfileController@updatePic')->name('picUpdate');

    Route::post('/detail-update/{id?}','ProfileController@updateDetail')->name('detailUpdate');

    Route::post('/password-update/{id?}','ProfileController@updatePass')->name('passUpdate');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Cache;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function categories(){
        return $this->hasMany('App\Category');
    }

    public function deliveries(){
        return $this->hasMany('App\Delivery');
    }

    public function delivery_mens(){
        return $this->hasMany('App\Delivery_men');
    }
    public function isOnline(){
        return Cache::has('user-is-online-' .$this->id);
    }
    public function orders(){
        return $this->hasMany('App\Order');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use App\Order;
use Hash;
use Auth;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index(Request $request)
    {
        $users = User::paginate(10);
        return view('user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name'=>'required|min:4|max:255',
            'password'=>'required|min:8|max:255|confirmed',
            'email'=>'required',
            'phone'=>'required',
            'image'=>'required|mimes:jpeg,png,pdf,jpg|max:8192',
        ]);
        $file = $request->image;
        $extension = $file->extension();
        $uuid = Str::uuid();
        $request->image->storeAs('/public', $uuid.".".$extension);
        $url = Storage::url($uuid.".".$extension);
        User::create([
            'name'=>$request->name,
            'password'=>bcrypt($request['password']),
            'email'=>$request->email,
            'phone'=>$request->phone,
            'image'=>$url,
        ]);
        Session::flash('success',"Created Successfully!");
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User::findOrFail($id);
        return view('user.show',compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,User $user)
    {  
        $this->authorize('edit',$user);
        return view('user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,User $user)
    {
        $this->authorize('edit',$user);
        $validatedData = $request->validate([
            'name'=>'required|min:4|max:255',
            'image'=>'mimes:jpeg,png,pdf|max:8192',
            'email'=>'required',
            'phone'=>'required',
    ]);
        $user->name=$request->name;
        $user->email=$request->email;
        if($request->password){
            $user->password = bcrypt($request->password);
        }else{
            $user->password;
        }
        $user->phone=$request->phone;
        if($request->image){
            $file = $request->image;
            $extension = $file->extension();
            $uuid = Str::uuid();
            $request->image->storeAs('/public', $uuid.".".$extension);
            $url = Storage::url($uuid.".".$extension);
            $user->image=$url;
        }
        $user->save();
        Session::flash('edit',"Edited Successfully!");
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        Session::flash('delete',"Deleted Successfully!");
        return redirect()->route('users.index');
    }

    public function search(Request $request){
        $order_0 = Order::where('state',0)->get()->count();
        $a = $request->user;
        $users = User::where('name','LIKE','%'.$a.'%')
                    ->orWhere('email','LIKE','%'.$a.'%')
                    ->orWhere('id','LIKE','%'.$a.'%')
                    ->paginate(10);
        return view('user.index',compact('users','order_0'));
        
    }

}

resources/views/user/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <h1>Create user</h1><br>
    <a href="{{ route('users.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="name" class="form-control" id="username" aria-describedby="nameHelp" value="{{ old('name') }}" placeholder="Enter a username">
            @error('name')
                <small id="nameHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="email">E-mail Address</label>
            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter your email" value="{{ old('email') }}">
            @error('email')
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="pwd">Password</label>
            <input type="password" name="password" class="form-control" id="pwd" aria-describedby="pwdHelp" placeholder="Enter a password" value="{{ old('password') }}">
            @error('password')
                <small id="pwdHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="password-confirm">Password Confirmation</label>
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password" placeholder="Retype the password again">
        </div>
        <div class="form-group">
            <label for="image">Choose your profile image</label>
            <input type="file" name="image" class="form-control" id="image" aria-describedby="imageHelp" value="{{ old('image') }}">
            @error('image')
                <small id="imageHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" name="phone" class="form-control" id="phone" aria-describedby="phHelp" placeholder="Enter a phone" value="{{ old('phone') }}">
            @error('phone')
                <small id="phHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <br>
    <h1>Edit user</h1>
    <a href="{{ route('users.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('users.update',$user->id) }}" method="post" enctype="multipart/form-data">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="name" class="form-control" id="username" aria-describedby="nameHelp" value="{{ $user->name }}">
            @error('name')
                <small id="nameHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="pwd">Password (If you dont want to change,dont fill anything.just leave a blank.)</label>
            <input type="password" name="password" class="form-control" id="pwd" aria-describedby="pwdHelp" placeholder="Enter a password">
            @error('password')
                <small id="pwdHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter your email" value="{{ $user->email }}">
            @error('email')
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="phone">Phone Number</label>
            <input type="text" name="phone" class="form-control" id="phone" aria-describedby="phHelp" placeholder="Enter a phone" value="{{ $user->phone }}">
            @error('phone')
                <small id="phHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="image">Choose your image</label>
            <input type="file" name="image" class="form-control" id="image" aria-describedby="imageHelp" value="{{ $user->image }}">
            @error('image')
                <small id="imageHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        @isset( $user->image )
            <div class="form-group">
                <label for="image">Images</label>
                <img src="{{ $user->image }}" style="height:100px;width:100px;">
            </div>
        @endif
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/user/index.blade.php
@extends('layouts.dashboard')
@section('asdf')
<meta http-equiv="refresh" content="708" />
@endsection
@section('title')
    Users
@endsection
@section('content')
    <nav class="navbar">
    <a href="{{ route('users.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;&nbsp;Create User</a>
        <form class="form-inline" action="/admin/search/users" method="get">
            <input class="form-control mr-3" name="user" type="search" placeholder="Search" aria-label="Search" list="users" autocomplete="off">
            <datalist id="users">
                @foreach($users as $user)
                    <option value="{{$user->name}}">{{ $user->name }}</option>
                @endforeach
            </datalist>
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav><br>
    @if(Session::has('success'))
        <p class="alert alert-success">{{ Session::get('success') }}</p>
    @endif
    @if(Session::has('delete'))
        <p class="alert alert-danger">{{ Session::get('delete') }}</p>
    @endif
    @if(Session::has('edit'))
        <p class="alert alert-info">{{ Session::get('edit') }}</p>
    @endif
        <table class="table table-striped text-center">
                        <thead class="bg-dark"> 
                            <tr>
                                <td>ID</td>
                                <td>Name</td>
                                <td>Email</td>
                                <td>Status</td>
                                <td>Phone</td>
                                <td>Created_at</td>
                                <td>Actions</td>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>
                                        <a href="" data-bs-toggle="modal" data-bs-target="#userModal-{{$user->id}}">
                                            <img src="{{ $user->image }}" width="35" height="35" style="border-radius:20px;">&nbsp;&nbsp;&nbsp;
                                        </a>
                                        <div class="modal fade" id="userModal-{{$user->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">{{ $user->name }}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <img src="{{$user->image}}" alt="food_image" height="460px" width="460px">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            </div>
                                            </div>
                                        </div>
                                        </div>    
                                        {{ $user->name }}    
                                    </td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @if($user->isOnline())
                                            <li class="text-success">Online</li>
                                        @else
                                            <li class="text-muted">Offline</li>
                                        @endif
                                    </td>
                                    <td>{{ $user->phone }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td class="d-flex justify-content-center">
                                    @if(Auth::user()->id==$user->id)
                                        <a href="{{ route('users.edit',$user->id) }}" class="btn btn-primary">
                                            <i class="far fa-edit"></i>
                                        </a>&nbsp;
                                        <form action="{{ route('users.destroy',$user->id) }}" method="post"> 
                                            @method('delete')
                                            @csrf 
                                            <button onclick="return confirm('Are you sure to delete this?')" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                                        </form>
                                    @else
                                        <p>&nbsp;</p>
                                    @endif
                                    </td>
                                </tr>
                            @empty
                            <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><h1>Unavailable Data TvT</h1></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                {{ $users->links() }}
@endsection

resources/views/user/show.blade.php
@extends('layouts.dashboard');
@section('content')
    <a href="{{ route('users.index') }}" class="btn btn-primary">Go Back</a><br><br>
        <b>ID : {{ $users->id }}</b><br>
        <b>Name : {{ $users->name }}</b><br>
        <b>Email : {{ $users->email}}</b><br>
        <b>Phone : {{ $users->phone }}</b><br>
        <b>Image : </b><br>
        <img src="{{ $users->image }}" alt="">
    </div>
@endsection