routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home',function(){
//     return view('welcome');
// });
// Route::get('/homee','HomeController@index');
Route::group(['prefix'=>'admin'],function(){
    Auth::routes(['verify'=>true,'register'=>true]);
});

Route::group(['middleware' => 'auth','prefix'=>'admin'],function(){

    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');

    Route::resource('/users','UserController');
    
    Route::resource('/categories','CategoryController');

    Route::resource('/foods','FoodController');

    Route::resource('/deliverymens','DeliverymenController');

    Route::resource('/deliveries','DeliveryController');

    Route::resource('/customers','CustomerController');

    Route::resource('/orderfoods','OrderfoodController');

    Route::get('/search/users','UserController@search');

    Route::get('/search/orderfoods','OrderfoodController@search');

    Route::get('/search/orders','OrderController@search');

    Route::get('/search/foods','FoodController@search');

    Route::get('/search/deliverymens','DeliverymenController@search');

    Route::get('/search/deliveries','DeliveryController@search');

    Route::get('/search/customers','CustomerController@search');

    Route::get('/search/categories','CategoryController@search');

    Route::get('/orders/active/{id?}','OrderController@active_order')->name('orders.active');

    Route::get('/orders/decline/{id?}','OrderController@decline_order')->name('orders.decline');

    Route::get('/deliverymens/available/{id?}','DeliverymenController@available')->name('deliverymens.available');

    Route::get('/deliverymens/unavailable/{id?}','DeliverymenController@unavailable')->name('deliverymens.unavailable');

    Route::get('/deliveries/finish/{id?}','DeliveryController@finish')->name('deliveries.finish');

    Route::resource('/orders',"OrderController"); 

});

Route::get('/login','Auth\LoginController@showCustomerLoginForm')->name('login.customer');

Route::post('/login','Auth\LoginController@customerLogin');

Route::get('/register','Auth\LoginController@showCustomerRegisterForm')->name('register.customer');

Route::post('/register','Auth\LoginController@customerRegister');

Route::post('/logout','Auth\LoginController@logout');

Route::view('/','frontend.index')->name('asdf');

Route::get('/shop/filter','FoodController@sortCategory');

Route::get('/shop','FoodController@allFood')->name('shop');

Route::view('/about','frontend.about');

Route::view('/contact','frontend.contact');

Route::group(['middleware' => ['auth:customer','verified']],function(){
    Route::get('/cart','OrderController@cart');

    Route::post('/gotocheck','OrderController@goToCheck')->name('gotocheck');

    Route::get('/orders','OrderController@allOrder')->name('order');

    Route::get('/orders/delete/{id?}','OrderController@destroyOrder');

    Route::get('/profile','ProfileController@index')->name('profile');

    Route::post('/profilepic-update/{id?}','ProfileController@updatePic')->name('picUpdate');

    Route::post('/detail-update/{id?}','ProfileController@updateDetail')->name('detailUpdate');

    Route::post('/password-update/{id?}','ProfileController@updatePass')->name('passUpdate');
});

app/Food.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;

class Food extends Model
{
    //
    protected $guarded = ['created_at','updated_at'];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function orders(){
        return $this->belongsToMany(Order::class,'order_foods');
    }
}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Food;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use App\Order;
use Stevebauman\Location\Facades\Location;


class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $foods = Food::with('category')->paginate(10);
        $order_0 = Order::where('state',0)->get()->count();
        return view('food.index',compact('foods'));
    }

    public function allFood()
    {
        $foods = Food::all();
        $categories = Category::all();
        return view('frontend.shop',compact('foods','categories'));
    }

    public function sortCategory(Request $request)
    {
        $categories = Category::all();
        $category_id = $request->category;
        $foods = Food::where('category_id',$category_id)->get();
        return view('frontend.shop',compact('foods','categories'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {  
        $categories = Category::all();
        return view('food.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'food_name'=>'required|min:4|max:255',
            'food_code'=>'required|integer',
            'image'=>'required|mimes:jpeg,png,pdf|max:8192',
            'price'=>'required|integer',
        ]);
        $file = $request->image;
        $extension = $file->extension();
        $uuid = Str::uuid();
        $request->image->storeAs('/public', $uuid.".".$extension);
        $url = Storage::url($uuid.".".$extension);
        Food::create([
            'food_name'=>$request->food_name,
            'food_code'=>$request->food_code,
            'image'=>$url,
            'price'=>$request->price,
            'ingredients'=>$request->ingredients,
            'category_id'=>$request->category_id
        ]);
        Session::flash('success',"Created Successfully");
        return redirect()->route('foods.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $foods = Food::findOrFail($id);
        return view('food.show',compact('foods'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $food = Food::findOrFail($id);
        return view('food.edit',compact('food','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'food_name'=>'required|min:4|max:255',
            'food_code'=>'required|integer',
            'image'=>'mimes:jpeg,png,pdf|max:8192',
            'price'=>'required|integer',
        ]);
        $food = Food::findOrFail($id);
        $food->food_name = $request->food_name;
        $food->food_code = $request->food_code;
        if($request['image']){
            $file = $request->image;
            $extension = $file->extension();
            $uuid = Str::uuid();
            $request->image->storeAs('/public', $uuid.".".$extension);
            $url = Storage::url($uuid.".".$extension);
            $food->image = $url;
        }
        $food->price = $request->price;
        $food->ingredients = $request->ingredients;
        $food->category_id = $request->category_id;
        $food->save();
        Session::flash('edit',"Edited Successfully");
        return redirect()->route('foods.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $food = Food::findOrFail($id);
        $food->delete();
        Session::flash('delete',"Deleted Successfully!");
        return redirect()->route('foods.index');
    }

    public function search(Request $request){
        $order_0 = Order::where('state',0)->get()->count();
        $a = $request->food;
        $foods = Food::where('id','LIKE','%'.$a.'%')
                    ->orWhere('food_name','LIKE','%'.$a.'%')
                    ->orWhere('food_code','LIKE','%'.$a.'%')
                    ->orWhere('category_id','LIKE','%'.$a.'%')
                    ->orWhere('price','LIKE','%'.$a.'%')
                    ->paginate(10);
        return view('food.index',compact('foods','order_0'));
        
    }
}

resources/views/food/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <br>
    <h1>Create a food</h1><br>
    <a href="{{ route('foods.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('foods.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="food_name">Food Name</label>
            <input type="text" name="food_name" class="form-control" id="food_name" aria-describedby="nameHelp" placeholder="Enter a food name" value="{{ old('food_name') }}">
            @error('food_name')
                <small id="nameHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="food_code">Food Code</label>
            <input type="text" name="food_code" class="form-control" id="food_code" aria-describedby="codeHelp" placeholder="Enter a food code" value="{{ old('food_code') }}">
            @error('food_code')
                <small id="codeHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="image">Choose your food image</label>
            <input type="file" name="image" class="form-control-file" id="image" aria-describedby="imageHelp" value="{{ old('image') }}">
            @error('image')
                <small id="imageHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="price">Food Price</label>
            <div class="input-group">
                <input type="text" name="price" class="form-control" id="price" aria-describedby="priceHelp" placeholder="Enter a food price" value="{{ old('price') }}">
                <span class="input-group-text">Kyats</span>
            </div>
            @error('price')
                <small id="priceHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="ingredients">Enter the ingredients</label>
            <textarea class="form-control" name="ingredients" id="ingredients" rows="5" placeholder="Enter the ingredients" aria-describedby="desHelp">{{ old('ingredients') }}</textarea>
            @error('ingredients')
                <small id="desHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
            <select class="custom-select" name="category_id">
                @foreach($categories as $category)
                <option name="category_id" value="{{ $category->id }}">{{$category->name}}</option>
                @endforeach
            </select>
            <br><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/food/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <br>
    <h1>Edit a food</h1><br>
    <a href="{{ route('foods.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('foods.update',$food->id) }}" method="post" enctype="multipart/form-data">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="food_name">Food Name</label>
            <input type="text" name="food_name" class="form-control" id="food_name" aria-describedby="nameHelp" placeholder="Enter a food name" value="{{ $food->food_name }}">
            @error('food_name')
                <small id="nameHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="food_code">Food Code</label>
            <input type="text" name="food_code" class="form-control" id="food_code" aria-describedby="codeHelp" placeholder="Enter a food code" value="{{ $food->food_code }}">
            @error('food_code')
                <small id="codeHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        
        
        <div class="form-group">
            <label for="image">Choose your food image</label>
            <input type="file" name="image" class="form-control-file" id="image" aria-describedby="imageHelp" value="{{ $food->image }}">
            @error('image')
                <small id="imageHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        @isset( $food->image )
            <div class="form-group">
                <label for="image">Images</label>
                <img src="{{ $food->image }}" style="height:100px;width:100px;">
            </div>
        @endif
        
        
        <div class="form-group">
            <label for="price">Food Price</label>
            <input type="text" name="price" class="form-control" id="price" aria-describedby="priceHelp" placeholder="Enter a food price" value="{{ $food->price }}">
            @error('price')
                <small id="priceHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="ingredients">Enter the ingredients</label>
            <textarea class="form-control" name="ingredients" id="ingredients" rows="5" placeholder="Enter the ingredients" aria-describedby="desHelp">{{ $food->ingredients }}</textarea>
            @error('ingredients')
                <small id="desHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
            <select class="custom-select" name="category_id">
                @foreach($categories as $category)
                    <!-- <option name="category_id" value="{{ $food->category_id }}">{{ $category->name }}</option> -->
                    @if($category->id==$food->category_id) 
                        <option name="category_id" value="{{$category->id}}" selected='selected'>{{$category->name}}</option>
                    @else
                        <option name="category_id" value="{{$category->id}}">{{ $category->name }}</option>
                    @endif
                @endforeach
            </select>
            <br><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/food/index.blade.php
@extends('layouts.dashboard')
@section('asdf')
<meta http-equiv="refresh" content="708" />
@endsection
@section('title')
    Foods
@endsection
@section('content')
    <nav class="navbar">
    <a href="{{ route('foods.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;&nbsp;Create food</a>
    <form class="form-inline" action="/admin/search/foods" method="get">
            <input list="foods" class="form-control mr-3" name="food" type="search" placeholder="Search" aria-label="Search" autocomplete="off">
            <datalist id="foods">
                @foreach($foods as $food)
                    <option value="{{$food->food_name}}">{{ $food->food_name }}</option>
                @endforeach
            </datalist>
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    </nav>
    <br>
    @if(Session::has('success'))
        <p class="alert alert-success">{{ Session::get('success') }}</p>
    @endif
    @if(Session::has('delete'))
        <p class="alert alert-danger">{{ Session::get('delete') }}</p>
    @endif
    @if(Session::has('edit'))
        <p class="alert alert-info">{{ Session::get('edit') }}</p>
    @endif
    <table class="table table-striped text-center">
                    <thead class="bg-dark">
                        <tr>
                            <td>ID</td>
                            <td>Name</td>
                            <td>Code</td>
                            <td>Price</td>
                            <td>Ingredients</td>
                            <td>Category</td>
                            <td>Actions</td>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($foods as $food)
                            <tr>
                                <td>{{ $food->id }}</td>
                                <td class="d-flex justify-content-center">
                                <div>
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#foodModal-{{$food->id}}">
                                        <img src="{{ $food->image }}" width=35px height=35px style="border-radius:20px;">
                                    </a>&nbsp;&nbsp;
                                </div>
                                    <div class="modal fade" id="foodModal-{{$food->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">{{ $food->food_name }}</h5>
                                            <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>
                                          </div>
                                          <div class="modal-body">
                                            <img src="{{$food->image}}" alt="food_image" height="460px" width="460px">
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                    <div>
                                        {{ $food->food_name }}
                                    </div>
                                    </td>
                                <td>{{ $food->food_code }}</td>
                                <td>{{ number_format($food->price) }} Kyats</td>
                                <td>{{ $food->ingredients }}</td>
                                <td>{{ $food->category->name }}</td>
                                <td class="d-flex justify-content-center">
                                    <a href="{{ route('foods.edit',$food->id) }}" class="btn btn-primary">
                                        <i class="far fa-edit"></i>
                                    </a>&nbsp;
                                    <form action="{{ route('foods.destroy',$food->id) }}" method="post"> 
                                        @method('delete')
                                        @csrf 
                                            <button onclick="return confirm('Are you sure to delete this?')" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><h1>Unavailable Data TvT</h1></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
                {{ $foods->links() }}
@endsection

resources/views/food/show.blade.php
@extends('layouts.dashboard');
@section('content')
    <a href="{{ route('foods.index') }}" class="btn btn-primary">Go Back</a><br>
        <b>ID : {{ $foods->id }}</b><br>
        <b>Food_Name : {{ $foods->food_name }}</b><br>
        <b>Food_code : {{ $foods->food_code}}</b><br>
    <img src="{{ $foods->image }}" alt=""><br>
        <b>Price : {{ $foods->price }}</b><br>
        <b>Ingredients : {{ $foods->ingredients }}</b><br>
        <b>Category_id : {{ $foods->category_id }}</b>
@endsection