routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home',function(){
//     return view('welcome');
// });
// Route::get('/homee','HomeController@index');
Route::group(['prefix'=>'admin'],function(){
    Auth::routes(['verify'=>true,'register'=>true]);
});

Route::group(['middleware' => 'auth','prefix'=>'admin'],function(){

    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');

    Route::resource('/users','UserController');
    
    Route::resource('/categories','CategoryController');

    Route::resource('/foods','FoodController');

    Route::resource('/deliverymens','DeliverymenController');

    Route::resource('/deliveries','DeliveryController');

    Route::resource('/customers','CustomerController');

    Route::resource('/orderfoods','OrderfoodController');

    Route::get('/search/users','UserController@search');

    Route::get('/search/orderfoods','OrderfoodController@search');

    Route::get('/search/orders','OrderController@search');

    Route::get('/search/foods','FoodController@search');

    Route::get('/search/deliverymens','DeliverymenController@search');

    Route::get('/search/deliveries','DeliveryController@search');

    Route::get('/search/customers','CustomerController@search');

    Route::get('/search/categories','CategoryController@search');

    Route::get('/orders/active/{id?}','OrderController@active_order')->name('orders.active');

    Route::get('/orders/decline/{id?}','OrderController@decline_order')->name('orders.decline');

    Route::get('/deliverymens/available/{id?}','DeliverymenController@available')->name('deliverymens.available');

    Route::get('/deliverymens/unavailable/{id?}','DeliverymenController@unavailable')->name('deliverymens.unavailable');

    Route::get('/deliveries/finish/{id?}','DeliveryController@finish')->name('deliveries.finish');

    Route::resource('/orders',"OrderController"); 

});

Route::get('/login','Auth\LoginController@showCustomerLoginForm')->name('login.customer');

Route::post('/login','Auth\LoginController@customerLogin');

Route::get('/register','Auth\LoginController@showCustomerRegisterForm')->name('register.customer');

Route::post('/register','Auth\LoginController@customerRegister');

Route::post('/logout','Auth\LoginController@logout');

Route::view('/','frontend.index')->name('asdf');

Route::get('/shop/filter','FoodController@sortCategory');

Route::get('/shop','FoodController@allFood')->name('shop');

Route::view('/about','frontend.about');

Route::view('/contact','frontend.contact');

Route::group(['middleware' => ['auth:customer','verified']],function(){
    Route::get('/cart','OrderController@cart');

    Route::post('/gotocheck','OrderController@goToCheck')->name('gotocheck');

    Route::get('/orders','OrderController@allOrder')->name('order');

    Route::get('/orders/delete/{id?}','OrderController@destroyOrder');

    Route::get('/profile','ProfileController@index')->name('profile');

    Route::post('/profilepic-update/{id?}','ProfileController@updatePic')->name('picUpdate');

    Route::post('/detail-update/{id?}','ProfileController@updateDetail')->name('detailUpdate');

    Route::post('/password-update/{id?}','ProfileController@updatePass')->name('passUpdate');
});

resources/views/orderdetail/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <br>
    <h1>Create a Orderdetail</h1><br>
    <a href="{{ route('orderfoods.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('orderfoods.store') }}" method="post">
        @csrf
        <div class="form-group">
            <select class="custom-select" name="food_id">
                <option selected>Choose a food</option>
                @foreach($foods as $food)
                    <option name="food_id" value="{{ $food->id }}" aria-describedBy="idHelp">{{ $food->food_name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="qty">Quantity</label>
            <input type="integer" name="qty" class="form-control" id="qty" aria-describedby="qtyHelp" placeholder="Enter a quantity" value="{{ old('qty') }}">
            @error('qty')
                <small id="qtyHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="rmk">Remark</label>
            <input type="text" name="rmk" class="form-control" id="rmk" aria-describedby="rmkHelp" placeholder="Enter a remark" value="{{ old('rmk') }}">
        @error('rmk')
                <small id="rmkHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <br>
        <div class="form-group">
            <select class="custom-select" name="order_id">
                <option selected>Choose an order</option>
                @foreach($orders as $order)
                    <option name="order_id" value="{{ $order->id }}">{{$order->id}}</option>
                @endforeach
            </select>
        </div><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/orderdetail/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <br>
    <h1>Edit a Orderdetail</h1><br>
    <a href="{{ route('orderfoods.index') }}" class="btn btn-primary">Go Back</a><br><br>
    <form action="{{ route('orderfoods.update',$orderdetail->id) }}" method="post">
        @method('put')
        @csrf
        <div class="form-group">
            <select class="custom-select" name="food_id">
                <option selected>Choose a food</option>
                @foreach($foods as $food)
                    @if($food->id == $orderdetail->food_id)
                        <option name="food_id" value="{{ $food->id }}" selected='selected'>{{ $food->food_name }}</option>
                    @else
                        <option name="food_id" value="{{ $food->id }}">{{ $food->food_name }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="qty">Quantity</label>
            <input type="integer" name="qty" class="form-control" id="qty" aria-describedby="qtyHelp" placeholder="Enter a quantity" value="{{ $orderdetail->qty }}">
            @error('qty')
                <small id="qtyHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" name="price" class="form-control" id="price" aria-describedby="priceHelp" placeholder="Enter a price" value="{{ $orderdetail->price }}">
            @error('price')
                <small id="priceHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <div class="form-group">
            <label for="rmk">Remark</label>
            <input type="text" name="rmk" class="form-control" id="rmk" aria-describedby="rmkHelp" placeholder="Enter a remark" value="{{ $orderdetail->rmk }}">
        @error('rmk')
                <small id="rmkHelp" class="form-text text-danger">{{ $message }}</small>
            @enderror
        </div>
        <br>
        <div class="form-group">
            <select class="custom-select" name="order_id">
                <option selected>Choose an order</option>
                @foreach($orders as $order)
                    @if($order->id == $orderdetail->order_id)
                        <option name="order_id" value="{{ $order->id }}" selected='selected'>{{$order->id}}</option>
                    @else
                        <option name="order_id" value="{{ $order->id }}">{{$order->id}}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
@endsection

resources/views/orderdetail/index.blade.php
@extends('layouts.dashboard')
@section('asdf')
<meta http-equiv="refresh" content="708" />
@endsection
@section('title')
    Order-details
@endsection
@section('content')
    <nav class="navbar">
    <a href="{{ route('orderfoods.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;&nbsp;Cant Create Orderdetail</a>
    <form class="form-inline" action="/admin/search/orderdetails" method="get">
            <input class="form-control mr-3" name="orderdetail" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    </nav>
    <br>
    @if(Session::has('success'))
        <p class="alert alert-success">{{ Session::get('success') }}</p>
    @endif
    @if(Session::has('delete'))
        <p class="alert alert-danger">{{ Session::get('delete') }}</p>
    @endif
    @if(Session::has('edit'))
        <p class="alert alert-info">{{ Session::get('edit') }}</p>
    @endif
    <table class="table table-striped">
                    <thead class="bg-dark">
                        <tr>
                            <td>ID</td>
                            <td>Order_id</td>
                            <td>&nbsp;&nbsp;&nbsp;Food</td>
                            <td>Quantity</td>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Price</td>
                            <td class="pl-5">Remark</td>
                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actions</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orderdetails as $orderdetail)
                            <tr>
                                <td>{{ $orderdetail->id }}</td>
                                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ $orderdetail->order_id }}</td>
                                <td>
                                    @foreach($foods as $food)
                                        @if($food->id == $orderdetail->food_id)
                                            {{ $food->food_name }}
                                        @endif
                                    @endforeach
                                </td>
                                <td class="pl-4">{{ $orderdetail->qty }}</td>
                                <td>{{ $orderdetail->price * $orderdetail->qty }} Kyats</td>
                                <td>{{ $orderdetail->rmk }}</td>
                                <td style="display:flex;">
                                    <a href="{{ route('orderfoods.edit',$orderdetail->id) }}" class="btn btn-primary">
                                        <i class="far fa-edit"></i>
                                    </a>&nbsp;&nbsp;
                                    <form action="{{ route('orderfoods.destroy',$orderdetail->id) }}" method="post"> 
                                        @method('delete')
                                        @csrf 
                                        <button onclick="return confirm('Are you sure to delete this?')" class="btn btn-danger"> <i class="far fa-trash-alt"></i></button>
                                    </form>
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $orderdetails->links() }}
@endsection

resources/views/orderdetail/show.blade.php
@extends('layouts.dashboard');
@section('content')
    <a href="{{ route('orderfoods.index') }}" class="btn btn-primary">Go Back</a><br><br>
        <b>ID : {{ $orderdetail->id }}</b><br>
        <b>Food_Id : {{ $orderdetail->food_id }}</b><br>
        <b>Quantity : {{ $orderdetail->qty}}</b><br>
        <b>Price : {{ $orderdetail->price }}</b><br>
        <b>Remark : {{ $orderdetail->rmk }}</b><br>
        <b>Order_id : {{ $orderdetail->order_id }}</b><br>
@endsection