routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/home',function(){
//     return view('welcome');
// });
// Route::get('/homee','HomeController@index');
Route::group(['prefix'=>'admin'],function(){
    Auth::routes(['verify'=>true,'register'=>true]);
});

Route::group(['middleware' => 'auth','prefix'=>'admin'],function(){

    Route::get('/dashboard','DashboardController@index')->name('dashboard.index');

    Route::resource('/users','UserController');
    
    Route::resource('/categories','CategoryController');

    Route::resource('/foods','FoodController');

    Route::resource('/deliverymens','DeliverymenController');

    Route::resource('/deliveries','DeliveryController');

    Route::resource('/customers','CustomerController');

    Route::resource('/orderfoods','OrderfoodController');

    Route::get('/search/users','UserController@search');

    Route::get('/search/orderfoods','OrderfoodController@search');

    Route::get('/search/orders','OrderController@search');

    Route::get('/search/foods','FoodController@search');

    Route::get('/search/deliverymens','DeliverymenController@search');

    Route::get('/search/deliveries','DeliveryController@search');

    Route::get('/search/customers','CustomerController@search');

    Route::get('/search/categories','CategoryController@search');

    Route::get('/orders/active/{id?}','OrderController@active_order')->name('orders.active');

    Route::get('/orders/decline/{id?}','OrderController@decline_order')->name('orders.decline');

    Route::get('/deliverymens/available/{id?}','DeliverymenController@available')->name('deliverymens.available');

    Route::get('/deliverymens/unavailable/{id?}','DeliverymenController@unavailable')->name('deliverymens.unavailable');

    Route::get('/deliveries/finish/{id?}','DeliveryController@finish')->name('deliveries.finish');

    Route::resource('/orders',"OrderController"); 

});

Route::get('/login','Auth\LoginController@showCustomerLoginForm')->name('login.customer');

Route::post('/login','Auth\LoginController@customerLogin');

Route::get('/register','Auth\LoginController@showCustomerRegisterForm')->name('register.customer');

Route::post('/register','Auth\LoginController@customerRegister');

Route::post('/logout','Auth\LoginController@logout');

Route::view('/','frontend.index')->name('asdf');

Route::get('/shop/filter','FoodController@sortCategory');

Route::get('/shop','FoodController@allFood')->name('shop');

Route::view('/about','frontend.about');

Route::view('/contact','frontend.contact');

Route::group(['middleware' => ['auth:customer','verified']],function(){
    Route::get('/cart','OrderController@cart');

    Route::post('/gotocheck','OrderController@goToCheck')->name('gotocheck');

    Route::get('/orders','OrderController@allOrder')->name('order');

    Route::get('/orders/delete/{id?}','OrderController@destroyOrder');

    Route::get('/profile','ProfileController@index')->name('profile');

    Route::post('/profilepic-update/{id?}','ProfileController@updatePic')->name('picUpdate');

    Route::post('/detail-update/{id?}','ProfileController@updateDetail')->name('detailUpdate');

    Route::post('/password-update/{id?}','ProfileController@updatePass')->name('passUpdate');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <scrip src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/1e9d4689e4.js" crossorigin="anonymous"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="{{ asset('https://code.jquery.com/jquery-3.6.0.min.js') }}"></script>
    <script>
    $(document).ready(function(){
        @stack('js_code')
    })
    </script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @yield('asdf')
    <title>Foodstagram | Admin Panel</title>
    <link href="{{asset('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css')}}" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="{{asset('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')}}">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.min.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <script src="{{asset('js/app.js')}}"></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed" oncontextmenu="return false">
<div class="wrapper">

  <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4" id="side-bar">
  <!-- Brand Logo -->
  <a href="#" class="brand-link">
    <img src="{{asset('dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Foodstagram</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
      <a href="{{ Auth::user()->image }}">
        <img src="{{ Auth::user()->image }}" class="img-circle elevation-2" alt="User Image">
      </a>
      </div>
      <div class="info">
        <a href="#" onclick="return alert('Hi , {{Auth::user()->name}} <3')" class="d-block">{{ Auth::user()->name }}</a>
      </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
              <li class="nav-item">
                <a href="{{ route('dashboard.index') }}" class="nav-link">
                  <i class="fas fa-columns nav-icon"></i>
                  <p>Dashboard</p>
                </a>
              </li>

            <li class="nav-item">
              <a href="{{ route('users.index') }}" class="nav-link">
                <i class="fas fa-user-astronaut nav-icon"></i>
                <p>User</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('categories.index') }}" class="nav-link">
                <i class="fas fa-stream nav-icon"></i>
                <p>Category</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('foods.index') }}" class="nav-link">
                <i class="fas fa-hamburger nav-icon"></i>
                <p>Food</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('orders.index') }}" class="nav-link">
                <i class="fas fa-clipboard-list nav-icon"></i>
                <p>Order</p>&nbsp;&nbsp;<span class="badge bg-info">{{App\Order::where('state',0)->get()->count()}}</span>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a href="{{ route('orderfoods.index') }}" class="nav-link">
                <i class="fas fa-info nav-icon"></i>
                <p>Order-Detail</p>
              </a>
            </li> -->
            <li class="nav-item">
              <a href="{{ route('customers.index') }}" class="nav-link">
                <i class="fas fa-users nav-icon"></i>
                <p>Customer</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('deliveries.index') }}" class="nav-link">
                <i class="fas fa-truck nav-icon"></i>
                <p>Delivery</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('deliverymens.index') }}" class="nav-link">
                <i class="fas fa-walking nav-icon"></i>
                <p>Deliveryman</p>
              </a>
            </li>
            <br>
            <form id="logout-form" action="{{ url('/logout') }}" method="post">
            @csrf
              <a class="btn btn-danger" id="logout_btn" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                  {{ __('Logout') }}
              </a>
            </form>
          <h6 style="font-size:11px;color:#869099;" class="text-center mt-4">Copyright &copy; 2021.All rights reserved.</h6>
        </ul>
    </nav>
  </div>
</aside>

 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
   <br>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-xxl-12 col-xl-12 col-12">
          <h1>@yield('title')</h1>
            @yield('content')
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
    <script src="{{asset('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js')}}" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('plugins/jquery-ui/jquery-ui.min.js')}}"></script>
    <script>
      $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('plugins/chart.js/Chart.min.js')}}"></script>
    <script src="{{asset('plugins/sparklines/sparkline.js')}}"></script>
    <script src="{{asset('plugins/jqvmap/jquery.vmap.min.js')}}"></script>
    <script src="{{asset('plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
    <script src="{{asset('plugins/jquery-knob/jquery.knob.min.js')}}"></script>
    <script src="{{asset('plugins/moment/moment.min.js')}}"></script>
    <script src="{{asset('plugins/daterangepicker/daterangepicker.js')}}"></script>
    <script src="{{asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
    <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
    <script src="{{asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
    <script src="{{asset('dist/js/adminlte.js')}}"></script>
    <script src="{{asset('dist/js/demo.js')}}"></script>
    <script src="{{asset('dist/js/pages/dashboard.js')}}"></script>
    <script src="{{asset('https://kit.fontawesome.com/68da0e5363.js')}}"></script>
    <script src="{{asset('js/style.js')}}"></script>  
    <script src="{{asset('https://code.highcharts.com/highcharts.js')}}"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    @stack('scripts')
    <script>
      $(document).ready(function(){
        setTimeout(function(){
           $("p.alert").remove();
        }, 4000 );
      })
    </script>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                @yield('content')
            </div>
        </div>
    </div>

</body>
</html>